Додав початкові файли notebook.py і notes_class.py
tru-ten/Personal_assistant pull request #4
Opened 2023-08-05 14:47 UTC by SergUs75

2023-08-06 17:20 UTC, tru-ten requested changes

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +        self.__value = None
Цей рядок коду потрібно видалити, оскільки він виходить зайвим

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +        return str(self.value)
Тут достатньо просто написати `return self.value`

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +    def __str__(self):
Цей метод потрібно видалити, оскільки він виходить зайвим. В класі **Field** вже існує такий метод, а отже в класі **Tag** цей метод вже наслідується. Можна подати в такому вигляді:

```
class Tag(Field):
    ...
```

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +    def __init__(self, name: Field, content: Field, tag: Tag = None):
Тут вже на ваш розсуд, або залишити як є, або подати в такому вигляді:

`def __init__(self, name: Field, content: Field, tag: Tag = None) -> None:`

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            "records": []
Тут можливо слід змінити назву ключа з **records** на **notes**

2023-08-06 17:20 UTC, bohdan-zhemelko commented on __pycache__/notes_class.cpython-311.pyc
Папку з кешем видаліть

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            json_record = {
Змінити назву змінної  з **json_record** на **json_note**

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            json_data["records"].append(json_record)
Враховуючи попередні синтаксичні зміни, рядок повинен виглядати наступним чином:

`json_data["notes"].append(json_note)`

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_main.py
> +    input("повернутися в Меню (натиснути Enter)")
Чому вирішили у цьому рядку так написати?Просто не розумію задум. Якщо ви хотіли гарно вивести у консолі, то як варіант, можна 10 рядок видалити, а у 9 рядку зробити наступним чином:

`print(note_book, '\n')`

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_main.py
> +    note_book.load_json('notebook.json')
Тут також не розумію задум. Правильно зрозумів, у проєкті ми вже самостійно створимо файл з таким іменем, щоб при початку роботи ми могли правильно зчитували дані? Якщо так, то не розумію для чого в класі **Notebook** в методі **load_json** ловити помилки **(FileNotFoundError, json.JSONDecodeError)**

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            "tags": list(tags_list),
Не розумію звідки ми беремо змінну **tags_list**

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +    def __eq__(self, other):
Для чого потрібен цей метод? Я не знайшов ніяке застосування для нього

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            print(f"The file {file_path} is missing or does not contain valid JSON data.")
Можу запропонувати зробити тут так, розбити ці винятки окремо. Коли виникає помилка **json.JSONDecodeError**, реалізувати таким чином:

```
except json.JSONDecodeError:
            print(f"The file {file_path} is missing or does not contain valid JSON data.")
```

У випадку **FileNotFoundError** реалізувати, якщо файлу немає, то потрібно його створити.

Але це лише у випадку якщо файлу не буде у проєкті створено автоматично.

2023-08-06 17:20 UTC, bohdan-zhemelko commented on notes_class.py
> +            return None
Цей рядок зайвий

2023-08-06 17:36 UTC, tru-ten requested changes

2023-08-06 17:36 UTC, tru-ten commented on notes_class.py
> +                global tags_list
Попередньо змінна tags_list в коді береться нізвідки, тому я гадаю до цієї частини коду інтерпретатор не добереться. Тому подумайте я виправити цю ситуацію з змінною tags_list

2023-08-06 18:14 UTC, SergUs75 commented on notes_class.py
> +        self.__value = None
зробив

2023-08-06 18:14 UTC, SergUs75 commented on notes_class.py
> +        return str(self.value)
зробив

2023-08-06 18:17 UTC, SergUs75 commented on notes_class.py
> +    def __str__(self):
зробив

2023-08-06 18:17 UTC, SergUs75 commented on notes_class.py
> +    def __init__(self, name: Field, content: Field, tag: Tag = None):
Зробив

2023-08-06 18:20 UTC, SergUs75 commented on notes_class.py
> +            "records": []
зробив

2023-08-06 18:22 UTC, SergUs75 commented on notes_class.py
> +            "tags": list(tags_list),
def load_json(self, file_path):
    
                    global tags_list
                tags_list = data["tags"]

2023-08-06 18:30 UTC, SergUs75 commented on notes_class.py
> +    def __eq__(self, other):
прибрав

2023-08-06 18:35 UTC, SergUs75 commented on notes_class.py
> +                global tags_list
буде потрібним пізніше для роботи з тегами, як словник

2023-08-06 19:00 UTC, SergUs75 commented on notes_class.py
> +            "tags": list(tags_list),
перероблено
class Notebook(UserDict):
    def __init__(self):
        self.data = {}
        self.tags_list = []
       
    def save_json(self, file_path):
            "tags": self.tags_list,
            
 def load_json(self, file_path):
     self.tags_list = data["tags"]

2023-08-06 19:15 UTC, SergUs75 commented on notes_main.py
> +    note_book.load_json('notebook.json')
json.JSONDecodeError залишилось коли писав save
FileNotFoundError потрібен для створоння чистої бази

2023-08-06 19:15 UTC, SergUs75 commented on notes_main.py
> +    note_book.load_json('notebook.json')
json.JSONDecodeError прибрав

2023-08-06 19:18 UTC, SergUs75 commented on notes_main.py
> +    input("повернутися в Меню (натиснути Enter)")
це попереднь дивився як завантажуються дані, там буде змінюватися

2023-08-06 19:20 UTC, SergUs75 commented on notes_class.py
> +            json_record = {
зробив

2023-08-06 19:20 UTC, SergUs75 commented on notes_class.py
> +            json_data["records"].append(json_record)
зробив

2023-08-06 19:24 UTC, SergUs75 commented on notes_main.py
> +    input("повернутися в Меню (натиснути Enter)")
input("повернутися в Меню (натиснути Enter)") для паузи щоб не завантажувалось меню

2023-08-06 19:25 UTC, SergUs75 commented on __pycache__/notes_class.cpython-311.pyc
добре

2023-08-06 19:26 UTC, SergUs75 commented on notes_class.py
> +                global tags_list
переробив

2023-08-09 09:34 UTC, tru-ten requested changes

2023-08-09 09:34 UTC, bohdan-zhemelko commented on notes_class.py
> +    def add_tag_note(self, new_tag):
Тут ви повторно створили вже існуючий метод

2023-08-09 09:34 UTC, bohdan-zhemelko commented on notes_class.py
> +            print(f"The file {file_path} is missing or does not contain valid JSON data.")
Якщо у користувача немає такого файлу, його варто створити, тому замість цього рядка викличте функцію **save_json**

2023-08-09 09:34 UTC, bohdan-zhemelko commented on notes_main.py
> +            user_input = get_input_int()
Цей рядок слід видалити

2023-08-09 09:34 UTC, bohdan-zhemelko commented on notes_main.py
> +            "\n4 - ain menu")
пропустили літеру m у слові main

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +            f"\n{'Note menu':.^40}"
Поміняйте цей рядок на ось цей `f"\n\n{'Note menu':.^40}"`

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +            f"\n{'Tag menu':.^40}"
Поміняйте цей рядок на ось цей `f"\n\n{'Tag menu':.^40}"`

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +        print(f"{name:.^40}"
Поміняйте цей рядок на ось цей `print(f"\n{name:.^40}"`

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +        print(f"{'Notebook menu:':.^40}"
Поміняйте цей рядок на ось цей `print(f"\n{'Notebook menu:':.^40}"`

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +            print(f"{'All notes':.^80}")
Поміняйте цей рядок на ось цей `print(f"\n{'All notes':.^80}")`

2023-08-09 09:34 UTC, tru-ten commented on notes_main.py
> +            print(f"{'Sort by tags':.^80}")
Поміняйте цей рядок на ось цей `print(f"\n{'Sort by tags':.^80}")`

2023-08-09 12:08 UTC, SergUs75 commented on notes_main.py
> +            print(f"{'Sort by tags':.^80}")
Зробив

2023-08-09 12:16 UTC, SergUs75 commented on notes_main.py
> +            "\n4 - ain menu")
Зробив

2023-08-09 15:42 UTC, SergUs75 commented on notes_main.py
> +            print(f"{'All notes':.^80}")
Зробив

2023-08-09 15:43 UTC, SergUs75 commented on notes_main.py
> +        print(f"{'Notebook menu:':.^40}"
Зробив

2023-08-09 15:43 UTC, SergUs75 commented on notes_main.py
> +        print(f"{name:.^40}"
Зробив

2023-08-09 15:43 UTC, SergUs75 commented on notes_main.py
> +            f"\n{'Tag menu':.^40}"
Зробив

2023-08-09 15:43 UTC, SergUs75 commented on notes_main.py
> +            f"\n{'Note menu':.^40}"
Зробив

2023-08-09 15:57 UTC, SergUs75 commented on notes_main.py
> +            user_input = get_input_int()
Зробив

2023-08-09 15:57 UTC, SergUs75 commented on notes_class.py
> +            print(f"The file {file_path} is missing or does not contain valid JSON data.")
зробив

2023-08-09 15:57 UTC, SergUs75 commented on notes_class.py
> +    def add_tag_note(self, new_tag):
зробив

2023-08-10 03:35 UTC, tru-ten approved these changes

2023-08-10 03:35 UTC, bohdan-zhemelko commented on __pycache__/notes_class.cpython-311.pyc
Слід видалити папку з кешем

2023-08-10 03:35 UTC, bohdan-zhemelko commented on notes_main.py
> +def edit_note(option, note):
Поміняйте цей метод на цей же, але з поправкою:

```
def edit_note(option, note):
    try:
        search_params = OPTIONS[option]
    except KeyError:
        return print("> Error: Invalid search parameter selected")    
    if not search_params:
        return print("> Error: Invalid search parameter selected") 
    if search_params[0] == "tags":
        return edit_tag(note)
    if search_params[0] == "status":
        return note_book.edit_status_in_note(note)  
    input_content = input(f"Enter search value for {search_params[0]} (format input: {search_params[1]}) >>> ")
    new_value = Field(input_content)
    note_book.edit_in_note(note, search_params[0], new_value)
```

2023-08-10 03:35 UTC, merged