Додано функціонал класів Phone, Birthday, Email
tru-ten/Personal_assistant pull request #6
Opened 2023-08-05 16:37 UTC by Olehsem23

1.  Для перевірки на правильність введення номеру телефону, використовуємо регулярний вираз, що українські номери обов'язково мають починатися з '+380' і ще 9 цифр. 
2. Для перевірки на правильність введення дати народження, необхідно щоб ми записували ці об'єкти як об'єкти типу datetime у форматі '%d.%m.%Y'. Це необхідно щоб одразу запобігти введенню 'дивних' даних на кшталт "2/2/42", '50.20.2000' чи навіть '29.02.2001'. Також варто уникати дат народження, які є у майбутньому. Це враховано у методі add_birthday класу Record.
3. Для перевірки на правильність введення email пропоную використати регулярний вираз, який був у нас у автоперевірці.
4. Додано відповідні методи у клас Record та команди, які потрібно вводити у терміналі, які записують дані для вибраного користувача. 
5. Додано рядкове представлення для виводу даних по записах (це лише моя пропозиція: варто обговорити, як краще це зробити).

2023-08-06 10:36 UTC, tru-ten requested changes

2023-08-06 10:36 UTC, bohdan-zhemelko commented on classes.py
> +    @property
Розгляньте такий варіант перевірки введення:

```
class Phone(Field):

    @Field.value.setter
    def value(self, value):
        if not re.match(r'^\+380\d{9}$', value):
            raise ValueError('Wrong format. Phone number should be in the format +380XXXXXXXXX.')
        self._Field__value = value
```

2023-08-06 10:36 UTC, bohdan-zhemelko commented on classes.py
> +    @property
Розгляньте такий варіант перевірки введення:

```
class Birthday(Field):

    @Field.value.setter
    def value(self, value):
        try:
            self._Field__value = datetime.strptime(value, '%d.%m.%Y').date()
        except ValueError:
            raise ValueError('Wrong format. Enter birthday in format dd.mm.YYYY. Days in range(31), month in range(12)')
```

2023-08-06 10:36 UTC, bohdan-zhemelko commented on classes.py
> +    @property
Розгляньте такий варіант перевірки введення:

```
class Email(Field):

    @Field.value.setter
    def value(self, value):
        if not re.match(r'[A-Za-z]{1}[\w.]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,}\b', value):
            raise ValueError('Wrong format. Email should be in the format xxxxxx@xxx.xx')
        self._Field__value = value
```

2023-08-06 10:36 UTC, bohdan-zhemelko commented on classes.py
> +    def add_birthday(self, birthday: Birthday):
Переробіть цю функцію, оскільки при вказуванні майбутньої дати воно всерівно присвоює цю дату користувачу, а повинно не дозволяти.

Ось як я проводив дебагінг:

**record = Record('name', '+380123456789')
birthday = Birthday('1.2.2024')
print(record.add_birthday(birthday))
record.add_birthday(birthday)
print(record)**

І ось, що отримав на виході:

![image](https://github.com/tru-ten/Personal_assistant/assets/74614544/ecd44929-e609-45f2-8a03-2f4cd9ec1d81)

2023-08-06 10:36 UTC, tru-ten commented on functions.py
>      'add': add_user,
Назвіть тут ключ `add user`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +    'show': show_user_command,
Назвіть тут ключ `show user`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +def add_phone_command(*args):  # Додаємо номер телефону для вибраного користувача.
Видаліть символ `*` при вказуванні аргументів, оскільки `*args` в даному випадку спримається як кортеж, а не як список через функцію `error_handler`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +def add_birthday_command(*args):  # додаємо дату народження для користувача
Видаліть символ `*` при вказуванні аргументів, оскільки `*args` в даному випадку спримається як кортеж, а не як список через функцію `error_handler`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +def add_email_command(*args):  # додаємо e-mail для користувача
Видаліть символ `*` при вказуванні аргументів, оскільки `*args` в даному випадку спримається як кортеж, а не як список через функцію `error_handler`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +def show_user_command(*args):  # Пошук телефона вибраного користувача.
Видаліть символ `*` при вказуванні аргументів, оскільки `*args` в даному випадку спримається як кортеж, а не як список через функцію `error_handler`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +    rec = Record(name)
Цей рядок і наступний потрібно видалити, тому що при роботі цього методу вони не знадобляться, оскільки запис з ім'ям користувача ми вже задаємо за допомогою функції `add user`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +    rec = Record(name)
Цей рядок і наступний потрібно видалити, тому що при роботі цього методу вони не знадобляться, оскільки запис з ім'ям користувача ми вже задаємо за допомогою функції `add user`

2023-08-06 10:36 UTC, tru-ten commented on functions.py
> +    rec = Record(name)
Цей рядок і наступний потрібно видалити, тому що при роботі цього методу вони не знадобляться, оскільки запис з ім'ям користувача ми вже задаємо за допомогою функції `add user`

2023-08-07 09:46 UTC, Olehsem23 commented on personal-assistant.py
Пропоную щоб ввід був трохи інформативнішим. і додав \n щоб була відстань між командами. так для сприйняття краще.

2023-08-07 09:53 UTC, Olehsem23 commented on contact_book_functions.py
> +        # щоб користувач знав у чому проблема. Крім того нам ще треба продумавти логіку для перехоплення помилок типу AttribiteError.
# Варто ще обробити помилки TypeError та AttribiteError. Вони точно будуть виникати під час роботи.

2023-08-07 09:57 UTC, Olehsem23 commented on contact_book_functions.py
> +        except ValueError as e:
Команда, яка видає список всіх доступних команд, щоб користувач міг легше зорієнтуватися.

2023-08-07 09:58 UTC, Olehsem23 commented on contact_book_functions.py
> +def exit(args):
перейменовано на exit_command

2023-08-07 10:02 UTC, Olehsem23 commented on contact_book_functions.py
> +    'add user': add_user,
Перероблено, щоб функції були ключами, а слова, якими ці команди викликаються - це tuple команд. Тепер можна дуже багато команд на виклик однієї команди навішати.

2023-08-07 10:02 UTC, Olehsem23 commented on contact_book_functions.py
> +def show_all(args):
rename to 'show_all_command'

2023-08-07 10:09 UTC, Olehsem23 commented on contact_book_functions.py
> +    if len(args)==2:
Додано фунції, які працюють з днями народженнями користувачів, та повертають відповідну інформацію.

2023-08-07 10:09 UTC, Olehsem23 commented on contact_book_functions.py
> +    'add phone': add_phone_command,
Додано звернення до функцій, які працюють з ДН.

2023-08-07 10:10 UTC, Olehsem23 commented on contact_book_functions.py
> +        if args:
Перероблено парсер, на вигляд який пропонував ментор на лекції. На мій погляд, так зручніше працювати.

2023-08-07 10:13 UTC, Olehsem23 commented on contact_book_classes.py
> +        except ValueError:
Додано перевірку на те, що дата народження не може бути у майбутньому.

2023-08-07 10:20 UTC, Olehsem23 commented on contact_book_classes.py
> +
Оновлено функцію, яка додає день народження користувача. умова про день народження у майбутньому перенесена в опис класу Birthday.

2023-08-07 10:25 UTC, Olehsem23 commented on contact_book_classes.py
> +class Record:
Додано функцію, яка повертає інформацію про кількість днів до дня народження користувача. Ще мені знадобилася додаткова фунція days_to_birthday_int_numbers, яка повертає лише числа. Вона нижче використовується, для методів класу AddressBook.

2023-08-07 10:28 UTC, Olehsem23 commented on contact_book_classes.py
> +    @Field.value.setter
Реалізовано функції, які також повертають списки працівників, котрі святкують ДН у вибраний період часу. Додатково фунції, які повертають список для поточного чи наступного тижня, та поточного та наступного місяця.

2023-08-07 10:56 UTC, Olehsem23 commented on contact_book_functions.py
> +def add_phone_command(args):  # Додаємо номер телефону для вибраного користувача.
все-таки потрібні ставити *args, бо без цього бере тільки перший символ і все.

2023-08-07 14:04 UTC, tru-ten requested changes

2023-08-07 14:04 UTC, bohdan-zhemelko commented on __pycache__/classes.cpython-311.pyc
Як я розумію цей файл виник коли ви робили дебагінг, тому можете його видалити

2023-08-07 14:04 UTC, bohdan-zhemelko commented on __pycache__/contact_book_classes.cpython-311.pyc
Як я розумію цей файл виник коли ви робили дебагінг, тому можете його видалити

2023-08-07 14:04 UTC, bohdan-zhemelko commented on __pycache__/contact_book_functions.cpython-311.pyc
Як я розумію цей файл виник коли ви робили дебагінг, тому можете його видалити

2023-08-07 14:04 UTC, bohdan-zhemelko commented on __pycache__/functions.cpython-311.pyc
Як я розумію цей файл виник коли ви робили дебагінг, тому можете його видалити

2023-08-07 14:04 UTC, tru-ten commented on personal-assistant.py
> +        user_input = input('\nEnter your command and args: ')
Варто додати до тексту input, що є така команда як help при натисканні якої видасть список команд. А то так виходить, що запускається бот, який вимагає команду, а користувач не знає які команди існують

2023-08-07 15:04 UTC, Olehsem23 commented on personal-assistant.py
> +        user_input = input('\nEnter your command and args: ')
Прийнято. Хоча я думаю, що краще це додати у привітальному повідомленні. Коли бот розказує про себе, що я вмію робити, якщо потрібно взнати перелік команд натисніть help. Хоча можна і там, і там це додати. Я напишу

2023-08-08 07:39 UTC, Olehsem23 commented on contact_book_functions.py
> +            return e
Додано функцію start

2023-08-08 07:40 UTC, Olehsem23 commented on contact_book_functions.py
> +def exit_command():
При виході з програми обовязково всі зміни зберігаються до файлу contact_book.bin

2023-08-08 08:29 UTC, bohdan-zhemelko requested changes

2023-08-08 08:29 UTC, bohdan-zhemelko commented on __pycache__/contact_book_classes.cpython-311.pyc
Слід видалити

2023-08-08 08:29 UTC, bohdan-zhemelko commented on __pycache__/contact_book_functions.cpython-311.pyc
Слід видалити

2023-08-08 08:29 UTC, bohdan-zhemelko commented on contact_book_functions.py
> +            return 'Not enough parameters'
Тут слід написати так `return 'First you should enter the username and, if necessary, the required parameter'`

2023-08-08 08:29 UTC, bohdan-zhemelko commented on contact_book_functions.py
> +            return f"No user with name {args[0]}. You need firstly create "
Тут слід написати так `return 'No user'`

2023-08-08 10:06 UTC, Olehsem23 commented on contact_book_functions.py
> +
Додав ще й до кожної команди номер. Тепер користувач коли викличе 'help', то він побачить що можна програму викликати різними методами. Наприклад, щоб додати телефон користувачу, він може набрати 'add phone', а може просто набрати '12' і це викличе програму на додавання телефону. Так само з усіма іншими.

2023-08-08 10:12 UTC, Olehsem23 commented on contact_book_classes.py
> +
Записує все у файл

2023-08-08 10:13 UTC, Olehsem23 commented on contact_book_classes.py
> +        bd_current_year = self.birthday.value.replace(year=today.year)
вивантажує всю інформацію за файлу для роботи.

2023-08-08 10:14 UTC, Olehsem23 commented on contact_book_classes.py
> +    # Рядкове представлення для одного запису у contact_book
Метод шукає задану послідовність символів по всій книзі. Виводить список де знайшло.

2023-08-08 20:44 UTC, tru-ten approved these changes

2023-08-08 20:44 UTC, merged